=== trufflesuite/truffle/packages/truffle-contract-schema/spec/contract-object.spec.json
{
  "id": "contract-object.spec.json",
  "$schema": "http://json-schema.org/schema#",
  "title": "Contract Object",
  "description": "Describes a contract consumable by Truffle, possibly including deployed instances on networks",

  "type": "object",
  "properties": {
    "contractName": {
      "allOf": [{ "$ref": "#/definitions/ContractName" }],
      "description": "Name used to identify the contract",
      "default": "Contract"
    },
    "abi": {
      "allOf": [{ "$ref": "abi.spec.json#" }],
      "description": "Interface description returned by compiler for source"
    },
    "bytecode": {
      "allOf": [{ "$ref": "#/definitions/Bytecode" }],
      "description": "Bytecode sent as contract-creation transaction data, with unresolved link references"
    },
    "deployedBytecode": {
      "allOf": [{ "$ref": "#/definitions/Bytecode" }],
      "description": "On-chain deployed contract bytecode, with unresolved link references" 
    },
    "sourceMap": {
      "allOf": [{ "$ref": "#/definitions/SourceMap" }],
      "description": "Source mapping for contract-creation transaction data bytecode"
    },
    "deployedSourceMap": {
      "allOf": [{ "$ref": "#/definitions/SourceMap" }],
      "description": "Source mapping for contract bytecode"
    },
    "source": { "$ref": "#/definitions/Source" },
    "sourcePath": { "$ref": "#/definitions/SourcePath" },
    "ast": { "$ref": "#/definitions/AST" },
    "legacyAST": { "$ref": "#/definitions/LegacyAST" },
    "compiler": {
      "type": "object",
      "properties": {
        "name": {"type": "string"},
        "version": {"type": "string"}
      }
    },
    "networks": {
      "patternProperties": {
        "^[a-zA-Z0-9]+$": { "$ref": "network-object.spec.json#" }
      },
      "additionalProperties": false
    },
    "schemaVersion": { "$ref": "#/definitions/SchemaVersion" },
    "updatedAt": {
      "type": "string",
      "format": "date-time"
    },
    "devdoc": { "$ref": "#/definitions/NatSpec" },
    "userdoc": { "$ref": "#/definitions/NatSpec" }
  },
  "required": [
    "abi"
  ],
  "patternProperties": {
    "^x-": { "anyOf": [
      { "type": "string" },
      { "type": "number" },
      { "type": "object" },
      { "type": "array" }
    ]}
  },
  "additionalProperties": false,

  "definitions": {
    "ContractName": {
      "type": "string",
      "pattern": "^[a-zA-Z_][a-zA-Z0-9_]*$"
    },

    "NatSpec": {
      "type": "object"
    },

    "Bytecode": {
      "type": "string",
      "pattern": "^0x0$|^0x([a-fA-F0-9]{2}|__.{38})+$"
    },

    "Source": {
      "type": "string"
    },

    "SourceMap": {
      "type": "string",
      "examples": [
        "315:637:1:-;;;452:55;;;;;;;-1:-1:-1;;;;;485:9:1;476:19;:8;:19;;;;;;;;;;498:5;476:27;;452:55;315:637;;;;;;;"
      ]
    },

    "SourcePath": {
      "type": "string"
    },

    "AST": {
      "type": "object"
    },

    "LegacyAST": {
      "type": "object"
    },

    "SchemaVersion": {
      "type": "string",
      "pattern": "[0-9]+\\.[0-9]+\\.[0-9]+"
    }
  }
}

=== trufflesuite/truffle/packages/truffle-contract-schema/test/MetaCoin.json
{
  "contractName": "MetaCoin",
  "abi": [
    {
      "inputs": [
        {
          "name": "addr",
          "type": "address"
        }
      ],
      "name": "getBalanceInEth",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "receiver",
          "type": "address"
        },
        {
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "sendCoin",
      "outputs": [
        {
          "name": "sufficient",
          "type": "bool"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "name": "addr",
          "type": "address"
        }
      ],
      "name": "getBalance",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "stateMutability": "nonpayable",
      "type": "constructor"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "_from",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "_to",
          "type": "address"
        },
        {
          "indexed": false,
          "name": "_value",
          "type": "uint256"
        }
      ],
      "name": "Transfer",
      "type": "event"
    }
  ],
  "bytecode": "0x6060604052341561000c57fe5b5b600160a060020a033216600090815260208190526040902061271090555b5b6102308061003b6000396000f300606060405263ffffffff60e060020a6000350416637bd703e8811461003757806390b98a1114610065578063f8b2cb4f14610098575bfe5b341561003f57fe5b610053600160a060020a03600435166100c6565b60408051918252519081900360200190f35b341561006d57fe5b610084600160a060020a036004351660243561014d565b604080519115158252519081900360200190f35b34156100a057fe5b610053600160a060020a03600435166101e5565b60408051918252519081900360200190f35b600073__ConvertLib____________________________6396e4ee3d6100eb846101e5565b60026000604051602001526040518363ffffffff1660e060020a028152600401808381526020018281526020019250505060206040518083038186803b151561013057fe5b6102c65a03f4151561013e57fe5b5050604051519150505b919050565b600160a060020a03331660009081526020819052604081205482901015610176575060006101df565b600160a060020a0333811660008181526020818152604080832080548890039055938716808352918490208054870190558351868152935191937fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef929081900390910190a35060015b92915050565b600160a060020a0381166000908152602081905260409020545b9190505600a165627a7a72305820f596963383bc39946413f0f0b34aee51796e6ae4b1b68b334f880b30a36ec6730029",
  "deployedBytecode": "0x606060405263ffffffff60e060020a6000350416637bd703e8811461003757806390b98a1114610065578063f8b2cb4f14610098575bfe5b341561003f57fe5b610053600160a060020a03600435166100c6565b60408051918252519081900360200190f35b341561006d57fe5b610084600160a060020a036004351660243561014d565b604080519115158252519081900360200190f35b34156100a057fe5b610053600160a060020a03600435166101e5565b60408051918252519081900360200190f35b600073__ConvertLib____________________________6396e4ee3d6100eb846101e5565b60026000604051602001526040518363ffffffff1660e060020a028152600401808381526020018281526020019250505060206040518083038186803b151561013057fe5b6102c65a03f4151561013e57fe5b5050604051519150505b919050565b600160a060020a03331660009081526020819052604081205482901015610176575060006101df565b600160a060020a0333811660008181526020818152604080832080548890039055938716808352918490208054870190558351868152935191937fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef929081900390910190a35060015b92915050565b600160a060020a0381166000908152602081905260409020545b9190505600a165627a7a72305820f596963383bc39946413f0f0b34aee51796e6ae4b1b68b334f880b30a36ec6730029",
  "sourceMap": "315:637:1:-;;;452:55;;;;;;;-1:-1:-1;;;;;485:9:1;476:19;:8;:19;;;;;;;;;;498:5;476:27;;452:55;315:637;;;;;;;",
  "source": "pragma solidity ^0.4.4;\n\nimport \"./ConvertLib.sol\";\n\n// This is just a simple example of a coin-like contract.\n// It is not standards compatible and cannot be expected to talk to other\n// coin/token contracts. If you want to create a standards-compliant\n// token, see: https://github.com/ConsenSys/Tokens. Cheers!\n\ncontract MetaCoin {\n\tmapping (address => uint) balances;\n\n\tevent Transfer(address indexed _from, address indexed _to, uint256 _value);\n\n\tfunction MetaCoin() {\n\t\tbalances[tx.origin] = 10000;\n\t}\n\n\tfunction sendCoin(address receiver, uint amount) returns(bool sufficient) {\n\t\tif (balances[msg.sender] < amount) return false;\n\t\tbalances[msg.sender] -= amount;\n\t\tbalances[receiver] += amount;\n\t\tTransfer(msg.sender, receiver, amount);\n\t\treturn true;\n\t}\n\n\tfunction getBalanceInEth(address addr) returns(uint){\n\t\treturn ConvertLib.convert(getBalance(addr),2);\n\t}\n\n\tfunction getBalance(address addr) returns(uint) {\n\t\treturn balances[addr];\n\t}\n}\n",
  "sourcePath": "/Users/gnidan/tmp/metacoin/contracts/MetaCoin.sol",
  "ast": {
    "children": [
      {
        "attributes": {
          "literals": [
            "solidity",
            "^",
            "0.4",
            ".4"
          ]
        },
        "id": 18,
        "name": "PragmaDirective",
        "src": "0:23:1"
      },
      {
        "attributes": {
          "file": "./ConvertLib.sol"
        },
        "id": 19,
        "name": "ImportDirective",
        "src": "25:26:1"
      },
      {
        "attributes": {
          "fullyImplemented": true,
          "isLibrary": false,
          "linearizedBaseContracts": [
            112
          ],
          "name": "MetaCoin"
        },
        "children": [
          {
            "attributes": {
              "constant": false,
              "name": "balances",
              "storageLocation": "default",
              "type": "mapping(address => uint256)",
              "visibility": "internal"
            },
            "children": [
              {
                "children": [
                  {
                    "attributes": {
                      "name": "address"
                    },
                    "id": 20,
                    "name": "ElementaryTypeName",
                    "src": "345:7:1"
                  },
                  {
                    "attributes": {
                      "name": "uint"
                    },
                    "id": 21,
                    "name": "ElementaryTypeName",
                    "src": "356:4:1"
                  }
                ],
                "id": 22,
                "name": "Mapping",
                "src": "336:25:1"
              }
            ],
            "id": 23,
            "name": "VariableDeclaration",
            "src": "336:34:1"
          },
          {
            "attributes": {
              "name": "Transfer"
            },
            "children": [
              {
                "children": [
                  {
                    "attributes": {
                      "constant": false,
                      "indexed": true,
                      "name": "_from",
                      "storageLocation": "default",
                      "type": "address",
                      "visibility": "internal"
                    },
                    "children": [
                      {
                        "attributes": {
                          "name": "address"
                        },
                        "id": 24,
                        "name": "ElementaryTypeName",
                        "src": "389:7:1"
                      }
                    ],
                    "id": 25,
                    "name": "VariableDeclaration",
                    "src": "389:21:1"
                  },
                  {
                    "attributes": {
                      "constant": false,
                      "indexed": true,
                      "name": "_to",
                      "storageLocation": "default",
                      "type": "address",
                      "visibility": "internal"
                    },
                    "children": [
                      {
                        "attributes": {
                          "name": "address"
                        },
                        "id": 26,
                        "name": "ElementaryTypeName",
                        "src": "412:7:1"
                      }
                    ],
                    "id": 27,
                    "name": "VariableDeclaration",
                    "src": "412:19:1"
                  },
                  {
                    "attributes": {
                      "constant": false,
                      "indexed": false,
                      "name": "_value",
                      "storageLocation": "default",
                      "type": "uint256",
                      "visibility": "internal"
                    },
                    "children": [
                      {
                        "attributes": {
                          "name": "uint256"
                        },
                        "id": 28,
                        "name": "ElementaryTypeName",
                        "src": "433:7:1"
                      }
                    ],
                    "id": 29,
                    "name": "VariableDeclaration",
                    "src": "433:14:1"
                  }
                ],
                "id": 30,
                "name": "ParameterList",
                "src": "388:60:1"
              }
            ],
            "id": 31,
            "name": "EventDefinition",
            "src": "374:75:1"
          },
          {
            "attributes": {
              "constant": false,
              "name": "MetaCoin",
              "payable": false,
